<?php
//require_once dirname(__FILE__) .'/../../src/model/TodoList.php';
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-12-02 at 13:20:37.
 */
class TodoListTest extends PHPUnit_Framework_TestCase {

    /**
     * @var TodoList
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new TodoList;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}
