<?php
//require_once dirname(__FILE__) .'/../../src/model/Todo.php';
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-12-02 at 13:20:37.
 */
class TodoTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Todo
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        date_default_timezone_set('UTC');
        $this->object = new Todo(-1, "sample", date("Y-m-d H:i:s", strtotime('2012-11-30 00:00:00')));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Todo::setLabels
     * @todo   Implement testSetLabels().
     */
    public function testSetLabels() {
        // Remove the following lines when you implement this test.
        $this->object->setLabels("label,important", ",");
        $this->assertContains("important", $this->object->labels);
        $this->assertNotContains("label,", $this->object->labels);
    }

}
