<?php
//require_once dirname(__FILE__) .'/../../src/utils/Util.php';
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-12-02 at 14:28:12.
 */
class UtilTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Util
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Util;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * Generated from @assert (1) == 2.
     *
     * @covers Util::diffDates
     */
    public function testDiffDates() {
        $this->assertEquals(
                2, Util::diffDates(1)
        );
    }

    /**
     * @expectedException Exception
     * @expectedExceptionMessage Missing parameter
     * @covers Util::diffDates
     */
    public function testDiffDatesException() {
        Util::diffDates(null);
    }

    /**
     * @covers Util::arrayToSQLOR
     * @todo   Implement testArrayToSQLOR().
     */
    public function testArrayToSQLOR() {
        // Remove the following lines when you implement this test.
        $this->assertEquals('(b=0 OR b=1 OR b=2 )', Util::arrayToSQLOR(array(0 => 0, 1 => 1, 2 => 2), 'b'));
    }

}
